logging:
  level:
    root: INFO

spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    password: pebs_2014
    username: root
#设置重启目录
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    
    
